name: Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *'  # 每 3 小时检查一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync with upstream
        uses: TG908/fork-sync@v1
        with:
          github_token: ${{ secrets.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 }}
          upstream: th2l-devs/lime  # 替换为上游仓库
          branch: main  # 要同步的分支
